---

  - local_action: file path=./ssl state=directory
    sudo: no

  - local_action: stat path=ssl/server.crt
    register: local_certificate
    sudo: no

  - name: create server key and certificate
    local_action: shell /bin/bash --login -c 'openssl req -new -nodes -x509 -subj "/C=/ST=/L=/O=/CN={{docker_registry_fqdn}}/subjectAltName=IP:{{docker_registry_ip}}" -days 3650 -keyout ./ssl/server.key -out ./ssl/server.crt -extensions v3_ca'
    sudo: no
    when: not local_certificate.stat.exists

  - copy: src=./ssl/{{item}} dest=/etc/nginx/ssl/
    with_items:
      - server.key
      - server.crt
