---

    - name: Install Prerequisites
      apt: >
        name={{ item }}
        state=installed
      with_items: 
        - build-essential
        - python-dev
        - libevent-dev
        - python-pip
        - liblzma-dev

    - name: Install and Configure Docker Registry
      pip: name=docker-registry

    - file: path=/var/lib/docker-registry state=directory

#    - name: stat docker-registry configuration file
#      stat: path=/usr/local/lib/python2.7/dist-packages/config/config.yml
#      register: docker_registry_config_stat

    - name: copy docker-registry configuration file
      copy: src=config.yml dest=/usr/local/lib/python2.7/dist-packages/config/config.yml
#      when: not docker_registry_config_stat.stat.exists
      notify:
      - restart docker-registry

    - file: path=/var/log/docker-registry state=directory

    - copy: src=docker-registry.conf dest=/etc/init/
      notify:
      - restart docker-registry

    - name: Secure Docker Registry with Nginx
      apt: >
        name={{item}}
        state=installed
      with_items:
        - nginx
        - python-passlib

    - htpasswd: path=/etc/nginx/docker-registry.htpasswd name={{item.name}} password={{item.password}} owner=root group=root mode=0644
      with_items: users

    - template: src=docker-registry.j2 dest=/etc/nginx/sites-available/docker-registry owner=root group=root mode=0644

    - file: src=/etc/nginx/sites-available/docker-registry dest=/etc/nginx/sites-enabled/docker-registry state=link
      notify:
      - restart nginx
